# Generated by Django 3.1.4 on 2020-12-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
